kvm: qemu: re-add missing declaration for vmchannel_init
The following patch re applies the declarations added to qemu/vl.h in
cbd2cefaf7b6185c3ebdb421a4cc4c363f6dbc39 and which were missed in merge
f4b21ce8084fc3ffcfc1a2b92bd26466700d3d40, resulting in the following
compilation warning :

  qemu/vl.c:9378: warning: implicit declaration of function `vmchannel_init'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>