kvm: qemu: re-add missing declaration for pci_hypercall_init
The following patch re applies the declarations added to qemu/vl.h in
2ea040d9b4a2f0642cb595898801d1abe6e47dc4 and which were missed in merge
f4b21ce8084fc3ffcfc1a2b92bd26466700d3d40, resulting in the following
compilation warning :

  qemu/hw/pc.c:1028: warning: implicit declaration of function `pci_hypercall_init'

Signed-off-by: Carlo Marcelo Arenas Belon <carenas@sajinet.com.pe>
Signed-off-by: Avi Kivity <avi@qumranet.com>