kvm: qemu: device-assignment: don't use libkvm's private get_slot()
get_slot() isn't exported by libkvm, so we shouldn't be using it.

The worst thing that can happen because of this change is that
libkvm will spew a warning. It looks to me like that can't happen
though.

Fixes:

  qemu/hw/device-assignment.c:161: warning: implicit declaration of function ‘get_slot’

Signed-off-by: Mark McLoughlin <markmc@redhat.com>
Signed-off-by: Avi Kivity <avi@redhat.com>